apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chainwise-public
  namespace: chainwise
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chainwise.dymonyx.ru
      secretName: chainwise-dymonyx-ru-tls
  rules:
    - host: chainwise.dymonyx.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
