apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - frontend.yaml
  - bike-api.yaml
  - maintenance-api.yaml
  - weather-api.yaml
  - reminder-api.yaml
  - user-api.yaml
images:
  - name: chainwise/frontend
    newName: agoneek/chainwise-frontend
    newTag: dev
  - name: chainwise/bike-api
    newName: agoneek/chainwise-bike-api
    newTag: dev
  - name: chainwise/maintenance-api
    newName: agoneek/chainwise-maintenance-api
    newTag: dev
  - name: chainwise/weather-api
    newName: agoneek/chainwise-weather-api
    newTag: dev
  - name: chainwise/reminder-api
    newName: agoneek/chainwise-reminder-api
    newTag: dev
  - name: chainwise/user-api
    newName: agoneek/chainwise-user-api
    newTag: dev